---
- name: Setup env specific variables
  set_fact:
    azure_ad_user: "{{ auth.username }}"
    azure_ad_pwd: "{{ auth.password }}"
    azure_sub_id: "{{ auth.subscription_id }}"
    region: "{{ cluster.region_name | default('eastus') }}"
    res_grp: "{{ cluster.resource_group }}"

- name: Delete a resource group
  azure_rm_resourcegroup:
    ad_user: "{{ azure_ad_user }}"
    password: "{{ azure_ad_pwd }}"
    subscription_id: "{{ azure_sub_id }}"
    name: "{{ res_grp }}"
    location: "{{ region }}"
    state: absent
    force: yes
