---
- name: Setup and initialize variables
  set_fact:
    current_host: "{{ hostvars[inventory_hostname].inter_name }}"
    peers: "{{ [] }}"

- name: Get peer container list
  set_fact:
    peers: |
      {{ peers + [{'org':item.split('@')[1].split('.')[-1],
        'name':item.split('@')[1] | replace('.', '-'),
        'role':item.split('@')[0]}] }}
  with_items: "{{ fabric.network[current_host].peers | default([]) }}"

- name: Setup few variables
  set_fact:
    fabricworkdir: "/opt/gopath/{{ env }}/fabric"
    fabricpath: "/opt/gopath/{{ env }}/src/github.com/hyperledger/fabric"
    gopath: "/opt/gopath/{{ env }}"
    localhome: "/home/{{ fabric.ssh_user }}/.composer"
    alladmin: ""
    peerorgs: "{{ peers | map(attribute='org') | list  | unique | sort }}"

- name: Generate all admin options
  set_fact:
    alladmin: "{{ alladmin + '-A ' + item + 'Admin -C /home/composer/.composer/' + item + 'Admin/admin-pub.pem ' }}"
  with_items: "{{ peerorgs }}"
  tags: "generatealladmin"

- name: Upload bna file
  copy:
    src: "{{ item }}"
    dest: "{{ fabricworkdir }}/keyfiles/"
  with_fileglob:
      - "{{ playbook_dir }}/../../secrets/networks/*.bna"
  tags: "uploadbna"

- name: Update bna on network
  command: >-
    docker run -v {{ localhome }}:/home/composer/.composer
    -v {{ fabricworkdir }}:{{ fabricworkdir }}
    hyperledger/composer-cli:next network update
    -c {{ peerorgs[0] }}Admin@{{ networkname }}
    -a {{ fabricworkdir }}/keyfiles/{{ networkname }}.bna
  tags: "updatebna"

