---
- name: Wait until servers are up and runnning
  wait_for:
    host: "{{ hostvars[item].ansible_host }}"
    port: "{{ hostvars[item].sshport }}"
    state: started
    delay: 5
    connect_timeout: 20
    timeout: 300
  with_items: "{{ groups['prohosts'] }}"
