# This compose file will deploy the services, and bootup a mongo server.

# Copyright IBM Corp., All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Local `/opt/cello/mongo` will be used for the db storage.
#  dashboard: dashboard service of cello, listen on 8080
#  app: app service of cello, listen on 80
#  nginx: front end
#  mongo: mongo db

version: '2'
services:
  # cello dashboard service
  watch-mode:
    image: hyperledger/cello-baseimage
    container_name: watch-mode
    volumes:  # This should be removed in product env
      - ./src/themes/react/static:/app
    command: bash -c "cd /app && npm run watch-mode"
