---
- name: Setup variables
  set_fact:
    fabricroot: "/opt/fabric"
    etcd_cluster: ""
    etcdtoken: "{{ lookup('password', '../../run/token chars=ascii_letters,digits length=8') }}"
    node_ip: "{{ hostvars[inventory_hostname].private_ip }}"
    node_name: "{{ hostvars[inventory_hostname].inter_name }}"

- name: Create etcd cluster parameter
  set_fact:
    etcd_cluster: "{{ etcd_cluster }} {{ hostvars[item].inter_name }}=http://{{ hostvars[item].private_ip }}:2380"
  with_items: "{{ groups['etcdnodes'] }}"

- name: Fix the spacing issues
  set_fact:
    etcd_cluster: "{{ etcd_cluster | trim | replace(' ', ',') }}"

- name: Ensure etcd service directory exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - "{{ fabricroot }}/bin/etcddata"

- name: Unpack etcd binaries
  unarchive:
    src: "{{ cluster.etcd_repo }}"
    dest: "{{ fabricroot }}/bin"
    remote_src: yes
    extra_opts: "--strip-components=1"
    exclude:
      - README-etcdctl.md
      - README.md
      - READMEv2-etcdctl.md
      - Documentation

- name: Config services
  template:
    src: "{{ playbook_dir }}/../env_flanneld/etcdsetup/templates/etcd.service.j2"
    dest: "/lib/systemd/system/etcd.service"
    mode: 0644

- name: Reload services
  command: systemctl daemon-reload

- name: Enable and start etcd services
  service:
    name: "etcd"
    enabled: yes
    state: restarted