---
- name: Setup variables
  set_fact:
    fabricpath: "/opt/gopath/{{ env }}/src/github.com/hyperledger/fabric"

- name: Setup hyperledger directory
  file:
    path: "{{ fabricpath }}/build"
    state: directory
    force: yes
    mode: 0775

- stat:
    path: "{{ fabricpath }}/build/bin/cryptogen"
  register: binexists

- name: Download fabric binaries
  unarchive:
    src: "{{ fabric.repo.bin }}"
    dest: "{{ fabricpath }}/build"
    remote_src: yes
  when: fabric.repo.bin|length > 0 and binexists.stat.exists == false
  tags: "downloadbin"

- name: Download kubectl
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v1.10.2/bin/linux/amd64/kubectl"
    dest: "{{ playbook_dir }}/../../vars/kubectl"
    mode: 0755
  tags: "downloadbin"
