---
- name: Prepare to run the workload
  hosts: cloud
  connection: local
  vars_files:
    - "./../../vars/{{ env }}.yml"
  tasks:
    - include_tasks: "prepare/tasks/main.yml"
  tags: "prepare"

- name: provision servers
  hosts: prohosts
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/../../vars/{{ env }}.yml"
  tasks:
    - include_tasks: "provision/tasks/{{ mode }}.yml"
  tags: "provision"

- name: Generate runhost file
  hosts: cloud
  connection: local
  vars_files:
    - "./../../vars/{{ env }}.yml"
  tasks:
    - include_tasks: "wait/tasks/{{ mode }}.yml"
  tags: "wait"

- name: Get VM IP addresses
  hosts: nathosts
  gather_facts: false
  user: "{{ cluster.ssh_user }}"
  vars_files:
    - "{{ playbook_dir }}/../../vars/{{ env }}.yml"
  tasks:
    - include_tasks: "netprocess/tasks/{{ mode }}.yml"
  tags: "netprocess"

- name: Generate runhost file
  hosts: cloud
  connection: local
  vars_files:
    - "./../../vars/{{ env }}.yml"
  tasks:
    - include_tasks: "post/tasks/{{ mode }}.yml"
  tags: "post"

- name: Setup hostname and static node names
  hosts: nathosts
  gather_facts: false
  user: "{{ cluster.ssh_user }}"
  become: true
  become_user: root
  vars_files:
    - "{{ playbook_dir }}/../../vars/{{ env }}.yml"
  tasks:
    - include_tasks: "namenode/tasks/{{ mode }}.yml"
  tags: "namenode"

- name: Setup certificates for ssh access
  hosts: nathosts
  gather_facts: false
  user: "{{ cluster.ssh_user }}"
  vars_files:
    - "{{ playbook_dir }}/../../vars/{{ env }}.yml"
  tasks:
    - include_tasks: "addcert/tasks/{{ mode }}.yml"
  tags: "addcert"
