---
- name: generate certificates
  hosts: cloud
  connection: local
  become: true
  become_user: root
  vars_files:
    - "./../../vars/{{ env }}.yml"
  tasks:
    - include_tasks: "getbin/tasks/{{ mode }}.yml"
  tags: "getbin"

- name: generate certificates
  hosts: cloud
  connection: local
  become: true
  become_user: root
  vars_files:
    - "./../../vars/{{ env }}.yml"
  tasks:
    - include_tasks: "../deploy_compose/certsetup/tasks/{{ mode }}.yml"
  tags: "certsetup"

- name: setup fabric network
  hosts: cloud
  connection: local
  become: true
  become_user: root
  vars_files:
    - "./../../vars/{{ env }}.yml"
  tasks:
    - include_tasks: "fabricsetup/tasks/{{ mode }}.yml"
  tags: "fabricsetup"

- name: setup composer
  hosts: cloud
  connection: local
  become: true
  become_user: root
  vars_files:
    - "./../../vars/{{ env }}.yml"
  tasks:
    - include_tasks: "composersetup/tasks/{{ mode }}.yml"
  tags: "composersetup"
