---
- name: Setup variables
  set_fact:
    goroot: "/opt/go"
    gopath: "/opt/gopath/{{ env }}"
    fabricworkdir: "/opt/gopath/{{ env }}/fabric"
    fabricpath: "/opt/gopath/{{ env }}/src/github.com/hyperledger/fabric"
    target: "{{ target | default('cryptogen,configtxgen') }}"

- name: Setup hyperledger directory
  file:
    path: "{{ fabricpath }}"
    state: directory
    force: yes
    mode: 0775

- name: Clean the build log file
  file:
    path: "{{ gopath }}/build.log"
    state: "absent"

- name: Ensure container image directory is clean
  file:
    path: "{{ fabricworkdir }}/images"
    state: "{{ item }}"
  with_items:
    - "absent"
    - "directory"

- name: Download fabric docker images
  include_tasks: "download.yml"
  when: fabric.baseimage_tag|length > 0
  tag: "downloadartifacts"

- name: build fabric artifacts
  include_tasks: "build.yml"
  when: fabric.baseimage_tag|length == 0
  tags: "buildartifacts"

- name: Setup hyperledger directory
  file:
    path: "{{ fabricpath }}/build"
    state: directory
    force: yes
    mode: 0775

- stat:
    path: "{{ fabricpath }}/build/bin/cryptogen"
  register: binexists

- name: Download fabric binaries
  unarchive:
    src: "{{ fabric.repo.bin }}"
    dest: "{{ fabricpath }}/build"
    remote_src: yes
  when: fabric.repo.bin|length > 0 and binexists.stat.exists == false
  tags: "downloadbin"

- name: Validate the version, baseimage_tag and helper_tag to be deployed
  fail:
    msg: >-
      the project version is empty, most likely configuration is not correct.
      Please check baseimage_tag and helper_tag are set correct or you set
      up to build fabric binaries and docker images!
  when: >
    project_version|length == 0 or baseimage_tag|length == 0 or
    helper_tag|length == 0

- name: Get all images for this deployment
  shell: >-
    docker images --format {% raw %}'{{.Repository}}:{{.Tag }}' {% endraw %}
    | grep 'hyperledger/fabric-' || :
  args:
    chdir: "{{ fabricpath }}"
  register: rawimages

- name: Save all the docker images
  shell: >-
    docker save -o {{ fabricworkdir }}/images/fabricimages.tar
    {{ rawimages.stdout_lines | join(' ') }}
  args:
    chdir: "{{ gopath }}"
  when: rawimages.stdout_lines|length > 0 and fabric.baseimage_tag == ''
  tags: "saveimages"

- name: Create the project version file
  template:
    src: "{{ playbook_dir }}/../deploy_compose/fabricbuild/templates/VERSION.j2"
    dest: "{{ fabricworkdir }}/images/VERSION"
