---
- name: fast initialize all the servers
  hosts: allnodes
  gather_facts: true
  strategy: free
  user: "{{ cluster.ssh_user }}"
  become: true
  become_user: root
  vars_files:
    - "./../../vars/{{ env }}.yml"
  tasks:
    - include_tasks: "../env_flanneld/fastinitnode/tasks/{{ mode }}.yml"
  tags: "fastinitnode"

- name: Setting up etcd services
  hosts: etcdnodes
  user: "{{ cluster.ssh_user }}"
  become: true
  become_user: root
  vars_files:
    - "./../../vars/{{ env }}.yml"
  tasks:
    - include_tasks: "../env_flanneld/etcdsetup/tasks/{{ mode }}.yml"
  tags: "etcdsetup"

- name: setup flanned on all nodes
  hosts: allnodes
  user: "{{ cluster.ssh_user }}"
  become: true
  become_user: root
  vars_files:
    - "./../../vars/{{ env }}.yml"
  tasks:
    - include_tasks: "networksetup/tasks/{{ mode }}.yml"
  tags: "networksetup"

- name: setup dns services
  hosts: allnodes
  user: "{{ cluster.ssh_user }}"
  become: true
  become_user: root
  vars_files:
    - "./../../vars/{{ env }}.yml"
  tasks:
    - include_tasks: "../env_flanneld/dnssetup/tasks/{{ mode }}.yml"
  tags: "dnssetup"
