apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: $networkName
  name: $podName
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: hyperledger
  template:
    metadata:
      labels:
        app: hyperledger
        role: orderer
        domain: $orgDomain
        orderer-id: $ordererID
    spec:
      containers:
      - name: $podName
        image: hyperledger/fabric-orderer:$fabVersion
        env:
        - name: FABRIC_LOGGING_SPEC
          value: DEBUG
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_LISTENPORT
          value: $listenPort
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /var/hyperledger/orderer/orderer.genesis.block
        - name: ORDERER_GENERAL_LOCALMSPID
          value: $localMSPID
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /var/hyperledger/orderer/msp
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /var/hyperledger/orderer/tls/server.key
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /var/hyperledger/orderer/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: '[/var/hyperledger/orderer/tls/ca.crt]'
        - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
          value: /var/hyperledger/orderer/tls/server.crt
        - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
          value: /var/hyperledger/orderer/tls/server.key
        - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
          value: '[/var/hyperledger/orderer/tls/ca.crt]'
        - name: GODEBUG
          value: netdns=go
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric
        ports:
         - containerPort: $containerPort
        command: ["orderer"]
        volumeMounts:
         - mountPath: /var/hyperledger/orderer/msp
           name: certificate
           subPath: $mspPath
         - mountPath: /var/hyperledger/orderer/tls
           name: certificate
           subPath: $tlsPath
         - mountPath: /var/hyperledger/orderer/orderer.genesis.block
           name: certificate
           subPath: genesis.block
         - mountPath: /var/hyperledger/production
           name: ordererdata
           subPath: $ordererDataPath
         - mountPath: /etc/localtime
           name: host-time
      volumes:
       - name: certificate
         persistentVolumeClaim:
             claimName: $credentialPV
       - name: ordererdata
         persistentVolumeClaim:
             claimName: $dataPV
       - name: host-time
         hostPath:
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: $ordererSvcName
  namespace: $networkName
spec:
 selector:
   app: hyperledger
   role: orderer
   orderer-id: $ordererID
   domain: $orgDomain
 type: NodePort
 ports:
   - name: listen-endpoint
     protocol: TCP
     port: $port
     targetPort: $targetPort
     nodePort: $nodePort


