---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $credentialPV
  labels:
    app: $credentialPV
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: $credentialPath
    server: $nfsServer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: $networkName
 name: $credentialPV
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Mi
 selector:
   matchLabels:
     app: $credentialPV

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $dataPV
  labels:
    app: $dataPV
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: $dataPath
    server: $nfsServer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: $networkName
 name: $dataPV
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Gi
 selector:
   matchLabels:
     app: $dataPV