---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-zoo-0-$networkName
  labels:
    app: zookeeper
    podindex: "0"
    network: $networkName
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: $path/zoo-0
    server: $nfsServer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-zoo-1-$networkName
  labels:
    app: zookeeper
    podindex: "1"
    network: $networkName
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: $path/zoo-1
    server: $nfsServer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-zoo-2-$networkName
  labels:
    app: zookeeper
    podindex: "2"
    network: $networkName
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: $path/zoo-2
    server: $nfsServer

