---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-zoo-0
  namespace: $networkName
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: zookeeper
      podindex: "0"
      network: $networkName
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-zoo-1
  namespace: $networkName
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: zookeeper
      podindex: "1"
      network: $networkName
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-zoo-2
  namespace: $networkName
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: zookeeper
      podindex: "2"
      network: $networkName
