---
- name: Reuse common code
  include_tasks: "{{ playbook_dir }}/../common/config_apply.yml"

- meta: end_play
  when: (allorderers | default([]) | length == 0) or (allpeers | default([]) | length == 0)

- name: Remove composer cli pod
  command: >-
    ./kubectl --kubeconfig=kubeconfig delete -f ../run/{{ item }}
  args:
    chdir: "{{ playbook_dir }}/../../vars/"
  with_items:
    - composercli.yaml
    - composerplayground.yaml
  when: (allorderers | length > 0) and (allpeers | length > 0)
  tags: "composerdown"
