---
- name: Setup variables
  set_fact:
    fabricpath: "/opt/fabric"
    etcd_cluster: ""
    node_ip: "{{ hostvars[inventory_hostname].private_ip }}"

- name: Ensure flanneld directory exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - "{{ fabricpath}}/bin"

- name: Get etcd ip address
  set_fact:
    etcd_ip: "{{ hostvars[groups['etcdnodes'][0]].private_ip }}"
  when: groups['etcdnodes'][0] is defined

- name: Reset etcd
  uri:
    url: "http://{{ etcd_ip }}:2379/v2/keys/{{ item }}?recursive=true"
    method: DELETE
    status_code: 200,202,204,404
  with_items:
    - coreos.com
  when: inventory_hostname == groups['allnodes'][0]

- name: Initialize the flanneld configuration in etcd
  uri:
    url: http://{{ etcd_ip }}:2379/v2/keys/coreos.com/network/config
    method: PUT
    body: >-
      value={{ cluster.container_network | to_nice_json(indent=2) }}
    status_code: 200,201
  when: inventory_hostname == groups['allnodes'][0]

- name: Create etcd cluster endpoint parameter
  set_fact:
    etcd_cluster: "{{ etcd_cluster }} http://{{ hostvars[item].private_ip }}:2379"
  with_items: "{{ groups['etcdnodes'] }}"

- name: Make the endpoint the right format
  set_fact:
    etcd_cluster: "{{ etcd_cluster | trim | replace(' ', ',') }}"

- name: Download flannel package
  get_url:
    url: "{{ cluster.flannel_repo }}"
    dest: "{{ fabricpath }}/bin/flanneld.tar.gz"
    force: no

- name: Unpack flannel binaries
  unarchive:
    src: "{{ fabricpath }}/bin/flanneld.tar.gz"
    dest: "{{ fabricpath }}/bin/"
    exclude:
      - README.me
      - mk-docker-opts.sh
    copy: no

- name: Configure flanneld services
  template:
    src: "{{ playbook_dir }}/../env_flanneld/networksetup/templates/flanneld.service.j2"
    dest: "/lib/systemd/system/flanneld.service"
    mode: 0644

- name: Change IP Forwarding
  command: iptables -P FORWARD ACCEPT

- name: Reload services
  command: systemctl daemon-reload

- name: Start the flanneld service
  service:
    name: flanneld
    enabled: yes
    state: started