---
- name: Find ip address position
  set_fact:
    ip_pos: "{{ inventory_hostname | replace(cluster.name_prefix, '') }}"

- name: Find the allocated IPs
  set_fact:
    ips: "{{ [cluster.node_ips[ip_pos|int-1]] | default([]) }}"

- name: Setup release floating IP flag
  set_fact:
    ip_flag: "{{ (ips == []) | ternary(true, false) }}"

- name: Destroy the OpenStack VM
  os_server:
    state: "absent"
    auth: "{{ auth }}"
    region_name: "{{ cluster.region_name }}"
    availability_zone: "{{ cluster.availability_zone }}"
    validate_certs: "{{ cluster.validate_certs }}"
    name: "{{ inventory_hostname }}"
    image: "{{ cluster.image_name }}"
    delete_fip: "{{ cluster.assign_public_ip | default(true) == false | ternary(false, ip_flag) }}"
    key_name: "fabric"
    timeout: 200
    network: "{{ cluster.private_net_name }}"
    meta:
      hostname: "{{ inventory_hostname }}"

- name: Destroy the OpenStack volume
  os_volume:
    state: absent
    auth: "{{ auth }}"
    region_name: "{{ cluster.region_name }}"
    availability_zone: "{{ cluster.availability_zone }}"
    validate_certs: "{{ cluster.validate_certs }}"
    wait: yes
    display_name: "{{ inventory_hostname }}_volume"
  when: cluster.volume_size > 0
