---
- name: Setup variables
  set_fact:
    fabricpath: "/opt/fabric"
    etcd_cluster: ""
    node_ip: "{{ hostvars[inventory_hostname].private_ip }}"
    index: 1
    as_ids: "{{ {} }}"

- name: Ensure calico directory exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - "{{ fabricpath}}/bin"

- name: Create AS number for calico node
  set_fact:
    as_ids: "{{ as_ids | combine({item: index}) }}"
    index: "{{ index | int + 1 }}"
  with_items: "{{ groups['allnodes'] }}"

- name: Get etcd ip address
  set_fact:
    etcd_ip: "{{ hostvars[groups['etcdnodes'][0]].private_ip }}"
  when: groups['etcdnodes'][0] is defined

- name: Reset etcd
  uri:
    url: "http://{{ etcd_ip }}:2379/v2/keys/{{ item }}?recursive=true"
    method: DELETE
    status_code: 200,202,204,404
  with_items:
    - calico
    - docker
  when: inventory_hostname == groups['allnodes'][0]

- name: Create etcd cluster endpoint parameter
  set_fact:
    etcd_cluster: "{{ etcd_cluster }} http://{{ hostvars[item].private_ip }}:2379"
  with_items: "{{ groups['etcdnodes'] }}"

- name: Make the endpoint the right format
  set_fact:
    etcd_cluster: "{{ etcd_cluster | trim | replace(' ', ',') }}"

- name: Get an etcd endpoint for docker cluster
  set_fact:
    etcd_endpoint: "etcd://{{ hostvars[ groups['etcdnodes'] | random ].private_ip }}:2379"

- name: Download calico binary
  get_url:
    url: "https://github.com/projectcalico/calicoctl/releases/download/v1.3.0/calicoctl"
    dest: "{{ fabricpath }}/bin/calicoctl"
    force: no

- name: Configure calico services
  template:
    src: "{{ playbook_dir }}/networksetup/templates/calico.service.j2"
    dest: "/lib/systemd/system/calico.service"
    mode: 0644

- name: Setup Docker service file
  template:
    src: "{{ playbook_dir }}/networksetup/templates/docker.j2"
    dest: "/lib/systemd/system/docker.service"
    mode: 0644

- name: Reload daemon service
  command: systemctl daemon-reload

- name: Restart the calico and docker services
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
    - docker.socket
    - docker
    - calico