---
- name: Setup env specific variables
  set_fact:
    aws_usr_key: "{{ auth.username }}"
    aws_sec_key: "{{ auth.password }}"

- name: Gather instances facts
  ec2_remote_facts:
    region: "{{ cluster.region_name }}"
    aws_access_key: "{{ aws_usr_key }}"
    aws_secret_key: "{{ aws_sec_key }}"
    filters:
      instance_state_name: running
      "tag:Name": "{{ inventory_hostname }}"
  register: vms

- name: Destroy the AWS EC2 VM
  ec2:
    region: "{{ cluster.region_name }}"
    aws_access_key: "{{ aws_usr_key }}"
    aws_secret_key: "{{ aws_sec_key }}"
    instance_id: "{{ vms.instances[0].id }}"
    state: absent
    wait_timeout: 200
    wait: true
  when: vms.instances | length > 0
