---
- name: Setup fabric root dir variable
  set_fact:
    fabricroot: "/opt/fabric"

- name: Stop the worker services
  service:
    name: "{{ item }}"
    enabled: yes
    state: stopped
  with_items:
    - kubelet
    - kube-proxy

- name: Ensure binary removed
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ fabricroot }}/bin/kubelet"
    - "{{ fabricroot }}/bin/kube-proxy"
    - "/etc/kubernetes"
    - "~/.kube"

- name: Check if there are dead containers
  command: docker ps -a -f status=exited -q
  register: deadcontainers

- name: Clean up the finished containers as well
  shell: docker rm -f $(docker ps -a -f status=exited -q)
  when: deadcontainers.stdout_lines | length > 0
  no_log: true
