---
- name: Check if the VirtualBox VM is already running
  shell: >-
    /usr/local/bin/VBoxManage list runningvms | grep {{ inventory_hostname }} | cat
  register: running

- name: Power off the VM
  command: >-
    /usr/local/bin/VBoxManage controlvm {{ inventory_hostname }} poweroff
  when: running.stdout != ""
  tags: "stopVM"

- name: Check if the VirtualBox VM already exists
  shell: >-
    /usr/local/bin/VBoxManage list vms | grep {{ inventory_hostname }} | cat
  register: exists

- name: Remove a VirtualBox VM
  command: >-
    /usr/local/bin/VBoxManage unregistervm {{ inventory_hostname }} --delete
  when: exists.stdout != ""
  tags: "removeVM"
