---
- name: Setup couple variables
  set_fact:
    public_ip: "{{ ansible_host }}"
    private_ip: "{{ hostvars[ansible_host].private_ip }}"
    fabricroot: "/opt/fabric"

- name: Remove dns reverse proxy
  command: >-
    docker rm -f fabricnginx
  ignore_errors: True

- name: Remove dns and dashboard services
  command: >-
    {{ fabricroot }}/bin/kubectl --server={{ private_ip }}:8080 delete
    -f /etc/kubernetes/{{ item }}.yaml
  with_items:
    - dnscontroller
    - dashboard
  no_log: true

# - name: Ensure deploy yaml files are removed
#  file:
#    path: "{{ item }}"
#    state: absent
#  with_items:
#    - "/etc/kubernetes/dashboard.yaml"
#    - "/etc/kubernetes/dnscontroller.yaml"