---
- name: Remove the fabric host files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ playbook_dir }}/../../run/fabrichosts"
    - "{{ playbook_dir }}/../../run/runhosts"

- name: Add the node to host group named allnodes
  add_host:
    name: "{{ hostvars[item].public_ip }}"
    private_ip: "{{ hostvars[item].private_ip }}"
    public_ip: "{{ hostvars[item].public_ip }}"
    inter_name: "{{ item[3:] }}"
    groups: "allnodes"
  with_items:
    - "{{ groups['nathosts'] }}"

- name: Setup runhosts file
  lineinfile:
    dest: "{{ playbook_dir }}/../../run/runhosts"
    create: yes
    insertafter: EOF
    line: "{{ item }}"
  with_items:
    - 'cloud ansible_host=127.0.0.1 ansible_python_interpreter=python'

- name: Add the node to host group with specified IP
  add_host:
    name: "{{ hostvars[item[0]].public_ip }}"
    private_ip: "{{ hostvars[item[0]].private_ip }}"
    public_ip: "{{ hostvars[item[0]].public_ip }}"
    inter_name: "{{ item[0][3:] }}"
    groups: "{{ item[1].type}}"
  when: item[0][3:] in item[1].member
  with_nested:
    - "{{ groups['nathosts'] }}"
    - [ { type: "etcdnodes", member: "{{ cluster.etcdnodes }}" },
        { type: "builders", member: "{{ cluster.builders }}"} ]

- name: Add all the hosts to the file
  lineinfile:
    dest: "{{ playbook_dir }}/../../run/runhosts"
    create: yes
    insertafter: EOF
    line: >-
      {{ hostvars[item].public_ip }}
      private_ip={{ hostvars[item].private_ip }}
      public_ip={{ hostvars[item].public_ip }}
      inter_name={{ hostvars[item].inter_name }}
  with_items:
    - "{{ groups['nathosts'] }}"

- name: Setup groups in the inventory file
  lineinfile:
    dest: "{{ playbook_dir }}/../../run/runhosts"
    insertafter: EOF
    regexp: 'NOT TO BE FOUND'
    state: present
    line: "{{ item }}"
  with_flattened:
    - ['', '[allnodes]', "{{ groups['allnodes'] }}"]
    - ['', '[etcdnodes]', "{{ groups['etcdnodes'] | default('') }}"]
    - ['', '[builders]', "{{ groups['builders'] | default('') }}"]

- name: Create the hosts file
  lineinfile:
    dest: "{{ playbook_dir }}/../../run/fabrichosts"
    create: yes
    insertafter: EOF
    line: >-
      {{ hostvars[item].private_ip }}
      {{ hostvars[item].inter_name }}
  with_items:
    - "{{ groups['nathosts'] }}"
