---
- name: Setup variables
  set_fact:
    etcd_cluster: ""
    node_ip: "{{ hostvars[groups['allnodes'][0]].private_ip }}"
    domain: "{{ (env_type|default('flanneld')=='flanneld') | ternary(cluster.domain, 'default.svc.'+cluster.domain) }}"

- name: Wait for the flannel to setup the subnets
  wait_for:
    path: /run/flannel/subnet.env
    search_regex: FLANNEL_SUBNET

- name: Get the bip address
  shell: >-
    . /run/flannel/subnet.env && echo $FLANNEL_SUBNET
  register: bip

- name: Get the mtu
  shell: >-
    . /run/flannel/subnet.env && echo $FLANNEL_MTU
  register: mtu

- name: Adding dns entry to the docker service
  template:
    src: "{{ playbook_dir }}/../env_flanneld/dnsdocker/templates/docker.j2"
    dest: "/lib/systemd/system/docker.service"

- name: Reload daemon service
  command: systemctl daemon-reload

- name: Restart the docker services
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
    - docker.socket
    - docker